version: '3'
services:
  zookeeper:
    image: qnib/plain-zookeeper:latest
    ports:
      - "2181:2181"
  zkui:
    image: qnib/plain-zkui:latest
    ports:
      - "9090:9090"
  broker:
    image: qnib/plain-kafka:latest
    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    ports:
      - "9092:9092"
    deploy:
      replicas: 1
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID={{.Task.Slot}}
  manager:
    image: qnib/plain-kafka-manager:latest
    ports:
      - "9000:9000"
    environment:
      ZOOKEEPER_HOSTS: "tasks.zookeeper:2181"
  producer:
    image: qnib/golang-kafka-producer:latest
    deploy:
      replicas: 3
    depends_on:
      - broker
    environment:
      - KAFKA_BROKER=tasks.broker
      - KAFKA_CREATE_TOPICS=test:1:1,scaled:2:2
      - KAFKA_TOPIC=scaled
      - MSG_COUNT=-1