apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jarvis-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jarvis-node
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: jarvis-node
        image: sreedal/jarvis-node:20
        ports:
        - containerPort: 8080
          name: broker
---
apiVersion: v1
kind: Service
metadata:
  name: jarvis-node
spec:
  type: LoadBalancer
  ports:
  - port: 82
    targetPort: 8080
  selector:
    app: jarvis-node
