apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: devenv
  name: devenv
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: devenv
    spec:
      containers:
      - args:
        - bash
        - -c
        - sleep 40 && jupyter nbconvert --execute --ExecutePreprocessor.timeout=-1
          --clear-output /home/jovyan/work/Jarvis/DevEnv_Prod.ipynb
        image: jupyter/tensorflow-notebook
        name: devenv
        ports:
        - containerPort: 8888
        resources: {}
        volumeMounts:
        - mountPath: /home/jovyan/work
          name: devenv-claim0
      restartPolicy: Always
      volumes:
      - name: devenv-claim0
        persistentVolumeClaim:
          claimName: devenv-claim0
status: {}
