apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jarvis-node
  name: jarvis-node
spec:
  ports:
  - name: "49160"
    port: 49160
    targetPort: 8080
  selector:
    io.kompose.service: jarvis-node
status:
  loadBalancer: {}
