apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: serving
  name: serving
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: serving
    spec:
      containers:
      - env:
        - name: MODEL_NAME
          value: half_plus_two
        image: tensorflow/serving
        name: serving
        ports:
        - containerPort: 8501
        resources: {}
        volumeMounts:
        - mountPath: /models/half_plus_two
          name: serving-claim0
      restartPolicy: Always
      volumes:
      - name: serving-claim0
        persistentVolumeClaim:
          claimName: serving-claim0
status: {}
